# GoReleaser configuration for Terraform Provider
# This file is used to build and release the provider binaries

version: 2

builds:
  - id: "terraform-provider-auth0-connections"
    binary: "terraform-provider-auth0-connections"
    main: .
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - id: "terraform-provider-auth0-connections"
    name_template: "terraform-provider-auth0-connections_{{.Version}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

release:
  github:
    owner: chc201627
    name: terraform-provider-auth0-connections
  draft: false
  prerelease: false
  name_template: "v{{.Version}}"
  mode: replace
  replace_existing_artifacts: true

signs:
  - artifacts: checksum
    signature: "${artifact}.sig"
    args: ["--batch", "--yes", "--detach-sign", "--armor", "--pinentry-mode", "loopback", "${artifact}"]

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
