# GoReleaser configuration for Terraform Provider
# This file is used to build and release the provider binaries

builds:
  - id: "terraform-provider-auth0-connections"
    binary: "terraform-provider-auth0-connections"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -ldflags=-s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0

archives:
  - id: "terraform-provider-auth0-connections"
    name_template: "terraform-provider-auth0-connections_{{.Version}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

# Terraform Registry specific configuration
terraform:
  provider_name: "auth0-connections"
  namespace: "chc201627"
  platforms:
    - "darwin_amd64"
    - "darwin_arm64"
    - "linux_amd64"
    - "linux_arm64"
    - "windows_amd64"
    - "windows_arm64"

release:
  github:
    owner: chc201627
    name: terraform-provider-auth0-connections
  draft: false
  prerelease: false
  name_template: "v{{.Version}}"
  mode: replace

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
